mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbname: test
  charset: utf8mb4

pool:
  size: 100 

redis:
  url: "localhost:6379"
  password: "yourpassword"
  db: 0
  pool:
    max_idle: 10
    max_active: 20
    idle_timeout: 300s

jwt:
  secret: "ukqwdugqwgudajduhqwe7128ye8y1p28e128qgdasdhba"
